language: haskell

before_install:
  - cabal update
  - cabal install happy alex tf-random QuickCheck
  - cabal install Agda-2.3.2.2  
  - agda --version

install:
  - /bin/true

script:
  - agda -i. README.agda
