language: haskell

before_install:
  - cabal install Agda-2.3.2.2  
  - agda --version
  - wget http://www.cse.chalmers.se/~nad/software/lib-0.7.tar.gz -O /tmp/lib-0.7.tar.gz
  - tar -xvf /tmp/lib-0.7.tar.gz
  - export PATH=$PATH:$HOME/build/agda/lib-0.7/src/

install:
  - /bin/true

script:
  - agda -i. README.agda
