language: haskell

before_install:
  - cabal install Agda-2.3.2.2  
  - agda --version
  - wget http://www.cse.chalmers.se/~nad/software/lib-0.7.tar.gz -O /tmp/lib-0.7.tar.gz
  - tar -xvf /tmp/lib-0.7.tar.gz

install:
  - /bin/true

script:
  - agda -i. -i /tmp/lib-0.7/src/ README.agda

notifications:
  email: false
